"""empty message

Revision ID: 3de8d1e63d22
Revises: 
Create Date: 2024-10-16 08:15:04.858623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de8d1e63d22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('curtain_status', sa.Boolean(), nullable=True),
    sa.Column('light_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('curtain_status', sa.Boolean(), nullable=True),
    sa.Column('light_status', sa.Boolean(), nullable=True),
    sa.Column('curtain_last_updated', sa.DateTime(), nullable=True),
    sa.Column('light_last_updated', sa.DateTime(), nullable=True),
    sa.Column('light_threshold', sa.Float(), nullable=True),
    sa.Column('curtain_auto', sa.Boolean(), nullable=True),
    sa.Column('light_auto', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    op.drop_table('room_details')
    # ### end Alembic commands ###
