"""empty message

Revision ID: 636a8c54a1fb
Revises: bc246a3ee9de
Create Date: 2024-10-16 07:14:32.205741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636a8c54a1fb'
down_revision = 'bc246a3ee9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.alter_column('curtain_last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('light_last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.alter_column('light_last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('curtain_last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
