"""empty message

Revision ID: bc246a3ee9de
Revises: ecc5cb961d59
Create Date: 2024-09-19 19:24:38.766310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc246a3ee9de'
down_revision = 'ecc5cb961d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('curtain_status', sa.Boolean(), nullable=True),
    sa.Column('light_status', sa.Boolean(), nullable=True),
    sa.Column('curtain_last_updated', sa.DateTime(), nullable=False),
    sa.Column('light_last_updated', sa.DateTime(), nullable=False),
    sa.Column('light_threshold', sa.Float(), nullable=True),
    sa.Column('curtain_auto', sa.Boolean(), nullable=True),
    sa.Column('light_auto', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    # ### end Alembic commands ###
